/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_string_test.check" instead.
 */

// #include <check.h>

#line 1 "s21_string_test.check"
#include "s21_string.h"

#include <check.h>
#include <errno.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

char buffer1[92] = {'\0'};
char buffer2[92] = {'\0'};
char str1[1024] = {'\0'};
char str2[1024] = {'\0'};

START_TEST(s21_memchr_test_1) {
#line 14
  char *str = "The five boxing wizards jump quickly.";
  char ch = 'l';
  ck_assert_pstr_eq(memchr(str, ch, 35), s21_memchr(str, ch, 35));
}
END_TEST

START_TEST(s21_memchr_test_2) {
#line 19
  char *str = "The five boxing wizards jump quickly.";
  char ch = 'o';
  ck_assert_pstr_eq(memchr(str, ch, 11), s21_memchr(str, ch, 11));
}
END_TEST

START_TEST(s21_memchr_test_3) {
#line 24
  char *str = "The five boxing wizards jump quickly.";
  char ch = ' ';
  ck_assert_pstr_eq(memchr(str, ch, 4), s21_memchr(str, ch, 4));
}
END_TEST

START_TEST(s21_memcmp_test_1) {
#line 29
  char str1[10] = "rtyvtytyny";
  char str2[10] = "rtYvtytyny";
  ck_assert_int_eq(memcmp(str1, str2, 5), s21_memcmp(str1, str2, 5));
}
END_TEST

START_TEST(s21_memcmp_test_2) {
#line 34
  char str5[10] = "-+-**yjtcc";
  char str6[10] = "iejyvteocy";
  ck_assert_int_eq(memcmp(str5, str6, 10), s21_memcmp(str5, str6, 10));
}
END_TEST

START_TEST(s21_memcmp_test_3) {
#line 39
  char str3[10] = "aegxesrhxd";
  char str4[10] = "aeg00srhxd";
  ck_assert_int_eq(memcmp(str3, str4, 7), s21_memcmp(str3, str4, 7));
}
END_TEST

START_TEST(s21_memcpy_test_1) {
#line 44
  char *dest[3] = {'\0'};
  char *dest2[3] = {'\0'};
  const char *src = "Hello, World!";
  int size = strlen(src) + 1;
  ck_assert_str_eq(s21_memcpy(dest, src, size), memcpy(dest2, src, size));
}
END_TEST

START_TEST(s21_memcpy_test_2) {
#line 51
  char dest[15] = {'\0'};
  char dest2[15] = {'\0'};
  const char *src = "Hello, World!";
  int size = strlen(src) + 1;
  int size2 = strlen(src) + 1;
  ck_assert_str_eq(s21_memcpy(dest, src, size), memcpy(dest2, src, size2));
}
END_TEST

START_TEST(s21_memcpy_test_3) {
#line 59
  char buffer[10] = {'\0'};
  char buffer2[10] = {'\0'};
  char *dest = buffer;
  char *dest2 = buffer2;
  char *src = buffer;
  int size = sizeof(buffer);
  int size2 = sizeof(buffer2);
  dest[0] = 'a';
  dest2[0] = 'a';
  src[0] = 'b';
  ck_assert_str_eq(s21_memcpy(dest, src, size), memcpy(dest2, src, size2));
}
END_TEST

START_TEST(s21_memcpy_test_4) {
#line 72
  const double src[5] = {1.1, 2.2, 3.3, 4.4, 5.5};
  double dest[5] = {'\0'};
  double dest2[5] = {'\0'};
  ck_assert_str_eq(s21_memcpy(dest, src, sizeof(src)),
                   memcpy(dest2, src, sizeof(src)));
}
END_TEST

START_TEST(s21_memset_test_1) {
#line 78
  char str[10] = {'\0'};
  ck_assert_ptr_eq(memset(str, 'A', sizeof(char) * 10),
                   s21_memset(str, 'A', sizeof(char) * 10));
}
END_TEST

START_TEST(s21_memset_test_2) {
#line 82
  char src[15] = "1234567890";
  ck_assert_ptr_eq(memset(src, '1', 10), s21_memset(src, '1', 10));
}
END_TEST

START_TEST(s21_memset_test_3) {
#line 86
  char str[10] = "123456789";
  ck_assert_ptr_eq(memset(str, 'A', sizeof(char) * 0),
                   s21_memset(str, 'A', sizeof(char) * 0));
}
END_TEST

START_TEST(s21_strncat_test_1) {
#line 90
  char dest[20] = "Hello";
  char src[] = "World";
  ck_assert_str_eq(strncat(dest, src, 3), s21_strncat(dest, src, 3));
}
END_TEST

START_TEST(s21_strncat_test_2) {
#line 95
  char dest[20] = "Hello";
  char src[] = "World";
  ck_assert_str_eq(strncat(dest, src, 0), s21_strncat(dest, src, 0));
}
END_TEST

START_TEST(s21_strncat_test_3) {
#line 100
  char dest[20] = "Hello";
  char src[] = "World";
  ck_assert_str_eq(strncat(dest, src, 5), s21_strncat(dest, src, 5));
}
END_TEST

START_TEST(s21_strchr_test_1) {
#line 105
  char *str = "The five boxing wizards jump quickly.";
  char ch = 'l';
  ck_assert_pstr_eq(strchr(str, ch), s21_strchr(str, ch));
}
END_TEST

START_TEST(s21_strchr_test_2) {
#line 110
  char *str = "The five boxing wizards jump quickly.";
  char ch = 'v';
  ck_assert_pstr_eq(strchr(str, ch), s21_strchr(str, ch));
}
END_TEST

START_TEST(s21_strchr_test_3) {
#line 115
  char *str = "The five boxing wizards jump quickly.";
  char ch = 'h';
  ck_assert_pstr_eq(strchr(str, ch), s21_strchr(str, ch));
}
END_TEST

START_TEST(s21_strchr_test_4) {
#line 120
  char *str = "The five boxing wizards jump quickly.";
  char ch = 'b';
  ck_assert_pstr_eq(strchr(str, ch), s21_strchr(str, ch));
}
END_TEST

START_TEST(s21_strchr_test_5) {
#line 125
  char *str = "The five boxing wizards jump quickly.";
  char ch = ' ';
  ck_assert_pstr_eq(strchr(str, ch), s21_strchr(str, ch));
}
END_TEST

START_TEST(s21_strlen_test_1) {
#line 130
  char str[20] = "ctycuyrcrcc";
  ck_assert_int_eq(s21_strlen(str), strlen(str));
}
END_TEST

START_TEST(s21_strlen_test_2) {
#line 134
  char str[20] = "hvty      ty";
  ck_assert_int_eq(s21_strlen(str), strlen(str));
}
END_TEST

START_TEST(s21_strlen_test_3) {
#line 138
  char str[20] = " * * / * - * ";
  ck_assert_int_eq(s21_strlen(str), strlen(str));
}
END_TEST

START_TEST(s21_strpbrk_test_1) {
#line 142
  char *str1 = "The five boxing wizards jump quickly.";
  char *str2 = "";
  ck_assert_pstr_eq(strpbrk(str1, str2), s21_strpbrk(str1, str2));
}
END_TEST

START_TEST(s21_strpbrk_test_2) {
#line 147
  char *str1 = "The five boxing wizards jump quickly.";
  char *str2 = "certc";
  ck_assert_pstr_eq(strpbrk(str1, str2), s21_strpbrk(str1, str2));
}
END_TEST

START_TEST(s21_strpbrk_test_3) {
#line 152
  char *str1 = "123456789";
  char *str2 = "4563";
  ck_assert_pstr_eq(strpbrk(str1, str2), s21_strpbrk(str1, str2));
}
END_TEST

START_TEST(s21_strpbrk_test_4) {
#line 157
  char *str1 = "The five boxing wizards jump quickly.";
  char *str2 = "tety*";
  ck_assert_pstr_eq(strpbrk(str1, str2), s21_strpbrk(str1, str2));
}
END_TEST

START_TEST(s21_strpbrk_test_5) {
#line 162
  char *str1 = "The five boxing wizards jump quickly.";
  char *str2 = " ";
  ck_assert_pstr_eq(strpbrk(str1, str2), s21_strpbrk(str1, str2));
}
END_TEST

START_TEST(s21_strerror_test_1) {
#line 167
  ck_assert_str_eq(s21_strerror(2), strerror(2));
}
END_TEST

START_TEST(s21_strerror_test_2) {
#line 170
  ck_assert_str_eq(s21_strerror(22), strerror(22));
}
END_TEST

START_TEST(s21_strerror_test_3) {
#line 173
  ck_assert_str_eq(s21_strerror(100), strerror(100));
}
END_TEST

START_TEST(s21_strncmp_test_1) {
#line 176
  const char *str10 = "Hello";
  const char *str20 = "Hello";
  ck_assert_int_eq(s21_strncmp(str10, str20, 5), strncmp(str10, str20, 5));
}
END_TEST

START_TEST(s21_strncmp_test_2) {
#line 181
  const char *str13 = "HFFlo";
  const char *str23 = "HFFlg";
  ck_assert_int_eq(s21_strncmp(str13, str23, 3), strncmp(str13, str23, 3));
}
END_TEST

START_TEST(s21_strncmp_test_3) {
#line 186
  const char *str111 = "Hello";
  const char *str222 = "Helld";
  ck_assert_int_eq(s21_strncmp(str111, str222, 4), strncmp(str111, str222, 4));
}
END_TEST

START_TEST(s21_strncmp_test_4) {
#line 191
  const char *str14 = "Hellp";
  const char *str24 = "Hello";
  ck_assert_int_eq(s21_strncmp(str14, str24, 3), strncmp(str14, str24, 3));
}
END_TEST

START_TEST(s21_strncmp_test_5) {
#line 196
  const char *str15 = "Hello World";
  const char *str25 = "Hello Everyone";
  ck_assert_int_eq(s21_strncmp(str15, str25, 5), strncmp(str15, str25, 5));
}
END_TEST

START_TEST(s21_strcspn_test_1) {
#line 201
  char str1[40] = "The five boxing wizards jump quickly.";
  char str2[40] = " ";
  ck_assert_int_eq(s21_strcspn(str1, str2), strcspn(str1, str2));
}
END_TEST

START_TEST(s21_strcspn_test_2) {
#line 206
  char str1[40] = "The five boxing wizards jump quickly.";
  char str2[40] = "The";
  ck_assert_int_eq(s21_strcspn(str1, str2), strcspn(str1, str2));
}
END_TEST

START_TEST(s21_strcspn_test_3) {
#line 211
  char str1[40] = "The five boxing wizards jump quickly.";
  char str2[40] = "jump";
  ck_assert_int_eq(s21_strcspn(str1, str2), strcspn(str1, str2));
}
END_TEST

START_TEST(s21_strncpy_test_1) {
#line 216
  char dest1[10] = {'\0'};
  char dest2[10] = {'\0'};
  char *src = "cefhvrtv";
  ck_assert_str_eq(strncpy(dest1, src, 9), s21_strncpy(dest2, src, 9));
}
END_TEST

START_TEST(s21_strncpy_test_2) {
#line 222
  char dest1[20] = {'\0'};
  char dest2[20] = {'\0'};
  char src1[] = "jyoloi";
  char src2[] = "jyoloi";
  ck_assert_str_eq(strncpy(dest1, src1, 6), s21_strncpy(dest2, src2, 6));
}
END_TEST

START_TEST(s21_strncpy_test_3) {
#line 229
  char dest1[50] = "The five boxing wizards jump quickly.";
  char dest2[50] = "The five boxing wizards jump quickly.";
  char src1[] = "sxthcetm";
  char src2[] = "sxthcetm";
  ck_assert_str_eq(strncpy(dest1, src1, 8), s21_strncpy(dest2, src2, 8));
}
END_TEST

START_TEST(s21_strrchr_test_1) {
#line 236
  char *str = "The five boxing wizards jump quickly.";
  char ch = 'o';
  ck_assert_pstr_eq(strrchr(str, ch), s21_strrchr(str, ch));
}
END_TEST

START_TEST(s21_strrchr_test_2) {
#line 241
  char *str = "The five boxing wizards jump quickly.";
  char ch = 'v';
  ck_assert_pstr_eq(strrchr(str, ch), s21_strrchr(str, ch));
}
END_TEST

START_TEST(s21_strrchr_test_3) {
#line 247
  char *str = "The five boxing wizards jump quickly.";
  char ch = 'T';
  ck_assert_pstr_eq(strrchr(str, ch), s21_strrchr(str, ch));
}
END_TEST

START_TEST(s21_strstr_test_1) {
#line 252
  char *haystack = "The five boxing wizards jump quickly..";
  char *ch = "The five boxing wizards jump quickly. certhcetyetycn tyv";
  ck_assert_pstr_eq(strstr(haystack, ch), s21_strstr(haystack, ch));
}
END_TEST

START_TEST(s21_strstr_test_2) {
#line 257
  char *haystack = "The five boxing wizards jump quickly.";
  char *ch = "g";
  ck_assert_pstr_eq(strstr(haystack, ch), s21_strstr(haystack, ch));
}
END_TEST

START_TEST(s21_strstr_test_3) {
#line 262
  char *haystack = "The five boxing wizards jump quickly.";
  char *ch = "five";
  ck_assert_pstr_eq(strstr(haystack, ch), s21_strstr(haystack, ch));
}
END_TEST

START_TEST(s21_strtok_test_1) {
#line 267
  char str[] = "The five boxing wizards*** jump quickly.";
  char *delim = "* ";
  ck_assert_str_eq(s21_strtok(str, delim), strtok(str, delim));
}
END_TEST

START_TEST(s21_strtok_test_2) {
#line 272
  char str[] = "The five boxing = wizards jump quickly.";
  char *delim = "= ";
  ck_assert_str_eq(s21_strtok(str, delim), strtok(str, delim));
}
END_TEST

START_TEST(s21_strtok_test_3) {
#line 277
  char str[] = "The five boxing wizards jump quickly.";
  char *delim = "e ";
  ck_assert_str_eq(s21_strtok(str, delim), strtok(str, delim));
}
END_TEST

START_TEST(s21_sprintf_test_d) {
#line 282
  sprintf(str1, "%d\n", 123);
  s21_sprintf(str2, "%d\n", 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%-d\n", 123);
  s21_sprintf(str2, "%-d\n", 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%+d\n", 123);
  s21_sprintf(str2, "%+d\n", 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "% d\n", 123);
  s21_sprintf(str2, "% d\n", 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%0d\n", 123);
  s21_sprintf(str2, "%0d\n", 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%10d\n", 123);
  s21_sprintf(str2, "%10d\n", 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%-10d\n", 123);
  s21_sprintf(str2, "%-10d\n", 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%+10d\n", 123);
  s21_sprintf(str2, "%+10d\n", 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "% 10d\n", 123);
  s21_sprintf(str2, "% 10d\n", 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%010d\n", 123);
  s21_sprintf(str2, "%010d\n", 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%.5d\n", 123);
  s21_sprintf(str2, "%.5d\n", 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%10.5d\n", 123);
  s21_sprintf(str2, "%10.5d\n", 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%-10.5d\n", 123);
  s21_sprintf(str2, "%-10.5d\n", 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%+10.5d\n", 123);
  s21_sprintf(str2, "%+10.5d\n", 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "% 10.5d\n", 123);
  s21_sprintf(str2, "% 10.5d\n", 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%10.5d\n", 123);
  s21_sprintf(str2, "%10.5d\n", 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%.*d\n", 5, 123);
  s21_sprintf(str2, "%.*d\n", 5, 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%*d\n", 10, 123);
  s21_sprintf(str2, "%*d\n", 10, 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%-*d\n", 10, 123);
  s21_sprintf(str2, "%-*d\n", 10, 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%+.*d\n", 5, 123);
  s21_sprintf(str2, "%+.*d\n", 5, 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%*.*d\n", 10, 5, 123);
  s21_sprintf(str2, "%*.*d\n", 10, 5, 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%-.*d\n", 5, 123);
  s21_sprintf(str2, "%-.*d\n", 5, 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%-*.5d\n", 10, 123);
  s21_sprintf(str2, "%-*.5d\n", 10, 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%+*d\n", 10, 123);
  s21_sprintf(str2, "%+*d\n", 10, 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%+*.*d\n", 10, 5, 123);
  s21_sprintf(str2, "%+*.*d\n", 10, 5, 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "% 10.*d\n", 5, 123);
  s21_sprintf(str2, "% 10.*d\n", 5, 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%-10.*d\n", 5, 123);
  s21_sprintf(str2, "%-10.*d\n", 5, 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%+10.*d\n", 5, 123);
  s21_sprintf(str2, "%+10.*d\n", 5, 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "% 10.*d\n", 5, 123);
  s21_sprintf(str2, "% 10.*d\n", 5, 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%10.*d\n", 5, 123);
  s21_sprintf(str2, "%10.*d\n", 5, 123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%+.*d\n", 5, -123);
  s21_sprintf(str2, "%+.*d\n", 5, -123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%.*d\n", 5, -123);
  s21_sprintf(str2, "%.*d\n", 5, -123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%10.*d\n", 5, -123);
  s21_sprintf(str2, "%10.*d\n", 5, -123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%-10.*d\n", 5, -123);
  s21_sprintf(str2, "%-10.*d\n", 5, -123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%+10.*d\n", 5, -123);
  s21_sprintf(str2, "%+10.*d\n", 5, -123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "% 10.*d\n", 5, -123);
  s21_sprintf(str2, "% 10.*d\n", 5, -123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%10.*d\n", 5, -123);
  s21_sprintf(str2, "%10.*d\n", 5, -123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%+d\n", -123);
  s21_sprintf(str2, "%+d\n", -123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "% d\n", -123);
  s21_sprintf(str2, "% d\n", -123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%-d\n", -123);
  s21_sprintf(str2, "%-d\n", -123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%0d\n", -123);
  s21_sprintf(str2, "%0d\n", -123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%10d\n", -123);
  s21_sprintf(str2, "%10d\n", -123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%-10d\n", -123);
  s21_sprintf(str2, "%-10d\n", -123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%+10d\n", -123);
  s21_sprintf(str2, "%+10d\n", -123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "% 10d\n", -123);
  s21_sprintf(str2, "% 10d\n", -123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%010d\n", -123);
  s21_sprintf(str2, "%010d\n", -123);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "Hello %hd", 23);
  s21_sprintf(str2, "Hello %hd", 23);
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "Hello %ld", 238230000006325000);
  s21_sprintf(str2, "Hello %ld", 238230000006325000);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test_s) {
#line 475
  sprintf(str1, "%s", "hello");
  s21_sprintf(str2, "%s", "hello");
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%10s", "hello");
  s21_sprintf(str2, "%10s", "hello");
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%-10s", "hello");
  s21_sprintf(str2, "%-10s", "hello");
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%.3s", "hello");
  s21_sprintf(str2, "%.3s", "hello");
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%10.3s", "hello");
  s21_sprintf(str2, "%10.3s", "hello");
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%s", "hello");
  s21_sprintf(str2, "%s", "hello");
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%-10.3s", "hello");
  s21_sprintf(str2, "%-10.3s", "hello");
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%s", "hello");
  s21_sprintf(str2, "%s", "hello");
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%5.3s", "hello");
  s21_sprintf(str2, "%5.3s", "hello");
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%5.3s", "hello");
  s21_sprintf(str2, "%5.3s", "hello");
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%-5s", "hello");
  s21_sprintf(str2, "%-5s", "hello");
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%5s", "hello");
  s21_sprintf(str2, "%5s", "hello");
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%s", "hello");
  s21_sprintf(str2, "%s", "hello");
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%s", "");
  s21_sprintf(str2, "%s", "");
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%s", "");
  s21_sprintf(str2, "%s", "");
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%.*s", 3, "hello, world");
  s21_sprintf(str2, "%.*s", 3, "hello, world");
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%s", "hello\n\tworld");
  s21_sprintf(str2, "%s", "hello\n\tworld");
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%s", "hello\"\\'world");
  s21_sprintf(str2, "%s", "hello\"\\'world");
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%s", "100%");
  s21_sprintf(str2, "%s", "100%");
  ck_assert_str_eq(str1, str2);

  sprintf(str1, "%s", "abc123!@#");
  s21_sprintf(str2, "%s", "abc123!@#");
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test_c) {
#line 556
  s21_sprintf(str2, "%1c", 'A');
  sprintf(str1, "%1c", 'A');
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%3c", 'B');
  sprintf(str1, "%3c", 'B');
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%-3c", 'C');
  sprintf(str1, "%-3c", 'C');
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%c", 'D');
  sprintf(str1, "%c", 'D');
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%c", 'E');
  sprintf(str1, "%c", 'E');
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%c", 'F');
  sprintf(str1, "%c", 'F');
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%c", 'G');
  sprintf(str1, "%c", 'G');
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%c", 'H');
  sprintf(str1, "%c", 'H');
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%c", 'I');
  sprintf(str1, "%c", 'I');
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%c", 'J');
  sprintf(str1, "%c", 'J');
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%c", 'K');
  sprintf(str1, "%c", 'K');
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%c", 'L');
  sprintf(str1, "%c", 'L');
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%cc", 'M');
  sprintf(str1, "%cc", 'M');
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%c", 'N');
  sprintf(str1, "%c", 'N');
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%c", 'O');
  sprintf(str1, "%c", 'O');
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%*c", 5, 'P');
  sprintf(str1, "%*c", 5, 'P');
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%c", 'Q');
  sprintf(str1, "%c", 'Q');
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%c", 'R');
  sprintf(str1, "%c", 'R');
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%-10c", 'S');
  sprintf(str1, "%-10c", 'S');
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%10c", 'T');
  sprintf(str1, "%10c", 'T');
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%c", 'U');
  sprintf(str1, "%c", 'U');
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test_u) {
#line 641
  s21_sprintf(str2, "No flags: %u", 12345);
  sprintf(str1, "No flags: %u", 12345);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Width 8: %8u", 12345);
  sprintf(str1, "Width 8: %8u", 12345);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Zero-padding, width 8: %08u", 12345);
  sprintf(str1, "Zero-padding, width 8: %08u", 12345);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Left align, width 8: %-8u", 12345);
  sprintf(str1, "Left align, width 8: %-8u", 12345);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Precision 5: %.5u", 12345);
  sprintf(str1, "Precision 5: %.5u", 12345);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Width 10, precision 5: %10.5u", 12345);
  sprintf(str1, "Width 10, precision 5: %10.5u", 12345);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Width 10, zero-padding, precision 5: %*.*u", 5, 10, 12345);
  sprintf(str1, "Width 10, zero-padding, precision 5: %*.*u", 5, 10, 12345);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Width 10, left align, precision 5: %-10.5u", 12345);
  sprintf(str1, "Width 10, left align, precision 5: %-10.5u", 12345);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Zero value: %u", 0);
  sprintf(str1, "Zero value: %u", 0);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Width 8, zero value: %8u", 0);
  sprintf(str1, "Width 8, zero value: %8u", 0);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Precision 5, zero value: %.5u", 0);
  sprintf(str1, "Precision 5, zero value: %.5u", 0);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Width 8, zero-padding, zero value: %08u", 0);
  sprintf(str1, "Width 8, zero-padding, zero value: %08u", 0);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Width 8, left align, zero value: %-8u", 0);
  sprintf(str1, "Width 8, left align, zero value: %-8u", 0);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Max unsigned int: %u", 4294967295U);
  sprintf(str1, "Max unsigned int: %u", 4294967295U);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Width 20, max unsigned int: %20u", 4294967295U);
  sprintf(str1, "Width 20, max unsigned int: %20u", 4294967295U);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Precision 20, max unsigned int: %.20u", 4294967295U);
  sprintf(str1, "Precision 20, max unsigned int: %.20u", 4294967295U);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Width 20, zero-padding, max unsigned int: %020u",
              4294967295U);
  sprintf(str1, "Width 20, zero-padding, max unsigned int: %020u", 4294967295U);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Width 20, left align, max unsigned int: %-20u",
              4294967295U);
  sprintf(str1, "Width 20, left align, max unsigned int: %-20u", 4294967295U);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Length h: %hu", (unsigned short)12345);
  sprintf(str1, "Length h: %hu", (unsigned short)12345);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Length h, width 10: %10hu", (unsigned short)12345);
  sprintf(str1, "Length h, width 10: %10hu", (unsigned short)12345);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Length h, precision 8: %.8hu", (unsigned short)12345);
  sprintf(str1, "Length h, precision 8: %.8hu", (unsigned short)12345);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Length h, width 10, precision 8: %10.8hu",
              (unsigned short)12345);
  sprintf(str1, "Length h, width 10, precision 8: %10.8hu",
          (unsigned short)12345);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Length h, width 10, left align, precision 8: %-10.8hu",
              (unsigned short)12345);
  sprintf(str1, "Length h, width 10, left align, precision 8: %-10.8hu",
          (unsigned short)12345);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Length l: %lu", 12345UL);
  sprintf(str1, "Length l: %lu", 12345UL);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Length l, width 10: %10lu", 12345UL);
  sprintf(str1, "Length l, width 10: %10lu", 12345UL);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Length l, precision 8: %.8lu", 12345UL);
  sprintf(str1, "Length l, precision 8: %.8lu", 12345UL);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Length l, width 10, precision 8: %10.8lu", 12345UL);
  sprintf(str1, "Length l, width 10, precision 8: %10.8lu", 12345UL);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Length l, width 10, left align, precision 8: %-10.8lu",
              12345UL);
  sprintf(str1, "Length l, width 10, left align, precision 8: %-10.8lu",
          12345UL);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Width 10, zero-padding, length h: %010hu",
              (unsigned short)12345);
  sprintf(str1, "Width 10, zero-padding, length h: %010hu",
          (unsigned short)12345);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "Width 10, zero-padding, length l: %010lu", 12345UL);
  sprintf(str1, "Width 10, zero-padding, length l: %010lu", 12345UL);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test_f) {
#line 762
  s21_sprintf(str2, "%f", 12345.6789);
  sprintf(str1, "%f", 12345.6789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%10f", 12345.6789);
  sprintf(str1, "%10f", 12345.6789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%010f", 12345.6789);
  sprintf(str1, "%010f", 12345.6789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%-10f", 12345.6789);
  sprintf(str1, "%-10f", 12345.6789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%.5f", 12345.6789);
  sprintf(str1, "%.5f", 12345.6789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%10.5f", 12345.6789);
  sprintf(str1, "%10.5f", 12345.6789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%-10.5f", 12345.6789);
  sprintf(str1, "%-10.5f", 12345.6789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%10.5f", 0.123456789);
  sprintf(str1, "%10.5f", 0.123456789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%-10.5f", 0.123456789);
  sprintf(str1, "%-10.5f", 0.123456789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%+.5f", 12345.6789);
  sprintf(str1, "%+.5f", 12345.6789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "% .5f", 12345.6789);
  sprintf(str1, "% .5f", 12345.6789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%#.5f", 12345.6789);
  sprintf(str1, "%#.5f", 12345.6789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%10.5f", 12345.0);
  sprintf(str1, "%10.5f", 12345.0);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%-10.5f", 12345.0);
  sprintf(str1, "%-10.5f", 12345.0);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%#.5f", -12345.0);
  sprintf(str1, "%#.5f", -12345.0);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%Lf", 12345.6789L);
  sprintf(str1, "%Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%10Lf", 12345.6789L);
  sprintf(str1, "%10Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%010Lf", 12345.6789L);
  sprintf(str1, "%010Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%-10Lf", 12345.6789L);
  sprintf(str1, "%-10Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%.5Lf", 12345.6789L);
  sprintf(str1, "%.5Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%10.5Lf", 12345.6789L);
  sprintf(str1, "%10.5Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%-10.5Lf", 12345.6789L);
  sprintf(str1, "%-10.5Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%10.5Lf", 0.123456789L);
  sprintf(str1, "%10.5Lf", 0.123456789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%-10.5Lf", 0.123456789L);
  sprintf(str1, "%-10.5Lf", 0.123456789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%+.5Lf", 12345.6789L);
  sprintf(str1, "%+.5Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "% .5Lf", 12345.6789L);
  sprintf(str1, "% .5Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%#.5Lf", 12345.6789L);
  sprintf(str1, "%#.5Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%10.5Lf", 12345.0L);
  sprintf(str1, "%10.5Lf", 12345.0L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%-10.5Lf", 12345.0L);
  sprintf(str1, "%-10.5Lf", 12345.0L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%#.5Lf", 12345.0L);
  sprintf(str1, "%#.5Lf", 12345.0L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "% f", 12345.6789);
  sprintf(str1, "% f", 12345.6789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%10.0f", 12345.6789);
  sprintf(str1, "%10.0f", 12345.6789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%.0f", 12345.6789);
  sprintf(str1, "%.0f", 12345.6789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%-10.0f", 12345.6789);
  sprintf(str1, "%-10.0f", 12345.6789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%010.0f", 12345.6789);
  sprintf(str1, "%010.0f", 12345.6789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%#010.0f", 12345.6789);
  sprintf(str1, "%#010.0f", 12345.6789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%010.2f", 12345.6789);
  sprintf(str1, "%010.2f", 12345.6789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%010.2f", 12345.6789);
  sprintf(str1, "%010.2f", 12345.6789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%0.2f", 12345.6789);
  sprintf(str1, "%0.2f", 12345.6789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%0.2f", 12345.6789);
  sprintf(str1, "%0.2f", 12345.6789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%+0.2f", 12345.6789);
  sprintf(str1, "%+0.2f", 12345.6789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "% 0.2f", 12345.6789);
  sprintf(str1, "% 0.2f", 12345.6789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%#0.2f", 12345.6789);
  sprintf(str1, "%#0.2f", 12345.6789);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%Lf", 12345.6789L);
  sprintf(str1, "%Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%10Lf", 12345.6789L);
  sprintf(str1, "%10Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%010Lf", 12345.6789L);
  sprintf(str1, "%010Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%-10Lf", 12345.6789L);
  sprintf(str1, "%-10Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%.5Lf", 12345.6789L);
  sprintf(str1, "%.5Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%10.5Lf", 12345.6789L);
  sprintf(str1, "%10.5Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%-10.5Lf", 12345.6789L);
  sprintf(str1, "%-10.5Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%10.5Lf", 0.123456789L);
  sprintf(str1, "%10.5Lf", 0.123456789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%-10.5Lf", 0.123456789L);
  sprintf(str1, "%-10.5Lf", 0.123456789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%+.5Lf", 12345.6789L);
  sprintf(str1, "%+.5Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "% .5Lf", 12345.6789L);
  sprintf(str1, "% .5Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%#.5Lf", 12345.6789L);
  sprintf(str1, "%#.5Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%10.5Lf", 12345.0L);
  sprintf(str1, "%10.5Lf", 12345.0L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%-10.5Lf", 12345.0L);
  sprintf(str1, "%-10.5Lf", 12345.0L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%#.5Lf", 12345.0L);
  sprintf(str1, "%#.5Lf", 12345.0L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "% f", (double)12345.6789L);
  sprintf(str1, "% f", (double)12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%10.0Lf", 12345.6789L);
  sprintf(str1, "%10.0Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%.0Lf", 12345.6789L);
  sprintf(str1, "%.0Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%-10.0Lf", 12345.6789L);
  sprintf(str1, "%-10.0Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%010.0Lf", 12345.6789L);
  sprintf(str1, "%010.0Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%#010.0Lf", 12345.6789L);
  sprintf(str1, "%#010.0Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%010.2Lf", 12345.6789L);
  sprintf(str1, "%010.2Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%010.2Lf", 12345.6789L);
  sprintf(str1, "%010.2Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%0.2Lf", 12345.6789L);
  sprintf(str1, "%0.2Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%0.2Lf", 12345.6789L);
  sprintf(str1, "%0.2Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%+0.2Lf", 12345.6789L);
  sprintf(str1, "%+0.2Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "% 0.2Lf", 12345.6789L);
  sprintf(str1, "% 0.2Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%#0.2Lf", 12345.6789L);
  sprintf(str1, "%#0.2Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%Lf", 12345.6789L);
  sprintf(str1, "%Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%10Lf", 12345.6789L);
  sprintf(str1, "%10Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%010Lf", 12345.6789L);
  sprintf(str1, "%010Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%-10Lf", 12345.6789L);
  sprintf(str1, "%-10Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%.5Lf", 12345.6789L);
  sprintf(str1, "%.5Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%10.5Lf", 12345.6789L);
  sprintf(str1, "%10.5Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%-10.5Lf", 12345.6789L);
  sprintf(str1, "%-10.5Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%10.5Lf", 0.123456789L);
  sprintf(str1, "%10.5Lf", 0.123456789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%-*.*Lf", 10, 5, 0.123456789L);
  sprintf(str1, "%-*.*Lf", 10, 5, 0.123456789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%+.5Lf", 12345.6789L);
  sprintf(str1, "%+.5Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "% .5Lf", 12345.6789L);
  sprintf(str1, "% .5Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%#.5Lf", 12345.6789L);
  sprintf(str1, "%#.5Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%10.5Lf", 12345.0L);
  sprintf(str1, "%10.5Lf", 12345.0L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%-10.5Lf", 12345.0L);
  sprintf(str1, "%-10.5Lf", 12345.0L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%#.5Lf", 12345.0L);
  sprintf(str1, "%#.5Lf", 12345.0L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "% Lf", 12345.6789L);
  sprintf(str1, "% Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%10.0Lf", 12345.6789L);
  sprintf(str1, "%10.0Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%.0Lf", 12345.6789L);
  sprintf(str1, "%.0Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%-10.0Lf", 12345.6789L);
  sprintf(str1, "%-10.0Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%010.0Lf", 12345.6789L);
  sprintf(str1, "%010.0Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%#010.0Lf", 12345.6789L);
  sprintf(str1, "%#010.0Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%010.2Lf", 12345.6789L);
  sprintf(str1, "%010.2Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%010.2Lf", 12345.6789L);
  sprintf(str1, "%010.2Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%0.2Lf", 12345.6789L);
  sprintf(str1, "%0.2Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%%%-.2Lf", 12345.6789L);
  sprintf(str1, "%%%-.2Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%+0.2Lf", 12345.6789L);
  sprintf(str1, "%+0.2Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "% 0.2Lf", 12345.6789L);
  sprintf(str1, "% 0.2Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);

  s21_sprintf(str2, "%#0.2Lf", 12345.6789L);
  sprintf(str1, "%#0.2Lf", 12345.6789L);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(s21_to_lower_test) {
#line 1159
  char *result16 = s21_to_lower("HELLO");
  ck_assert_str_eq(result16, "hello");
  free(result16);

  char *result17 = s21_to_lower("HeLLo WOrLD");
  ck_assert_str_eq(result17, "hello world");
  free(result17);

  char *result18 = s21_to_lower("1234");
  ck_assert_str_eq(result18, "1234");
  free(result18);

  char *result19 = s21_to_lower("");
  ck_assert_str_eq(result19, "");
  free(result19);

  char *result20 = s21_to_lower(NULL);
  ck_assert_ptr_null(result20);
  free(result20);
}
END_TEST

START_TEST(s21_to_upper_test) {
#line 1181
  char *result1 = s21_to_upper("hello");
  ck_assert_str_eq(result1, "HELLO");
  free(result1);

  char *result2 = s21_to_upper("HeLLo WOrLD");
  ck_assert_str_eq(result2, "HELLO WORLD");
  free(result2);

  char *result3 = s21_to_upper("1234");
  ck_assert_str_eq(result3, "1234");
  free(result3);

  char *result4 = s21_to_upper("");
  ck_assert_str_eq(result4, "");
  free(result4);

  char *result5 = s21_to_upper(NULL);
  ck_assert_ptr_null(result5);
  free(result5);
}
END_TEST

START_TEST(s21_insert_test) {
#line 1202
  char *result6 = s21_insert("Hello", "World", 5);
  ck_assert_str_eq(result6, "HelloWorld");
  free(result6);

  char *result7 = s21_insert("Hello World", " beautiful", 5);
  ck_assert_str_eq(result7, "Hello beautiful World");
  free(result7);

  char *result8 = s21_insert("World", "Hello ", 0);
  ck_assert_str_eq(result8, "Hello World");
  free(result8);

  char *result9 = s21_insert("Hello", " World", 5);
  ck_assert_str_eq(result9, "Hello World");
  free(result9);

  char *result10 = s21_insert(NULL, "Hello", 0);
  ck_assert_ptr_null(result10);
  free(result10);
}
END_TEST

START_TEST(s21_trim_test) {
#line 1223
  char *result11 = s21_trim("  Hello  ", " ");
  ck_assert_str_eq(result11, "Hello");
  free(result11);

  char *result12 = s21_trim("---Hello---", "-");
  ck_assert_str_eq(result12, "Hello");
  free(result12);

  char *result13 = s21_trim("", " ");
  ck_assert_str_eq(result13, "");
  free(result13);

  char *result14 = s21_trim(NULL, " ");
  ck_assert_ptr_null(result14);
  free(result14);

  char *result15 = s21_trim("Hello", "");
  ck_assert_str_eq(result15, "Hello");
  free(result15);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_memchr_test_1);
  tcase_add_test(tc1_1, s21_memchr_test_2);
  tcase_add_test(tc1_1, s21_memchr_test_3);
  tcase_add_test(tc1_1, s21_memcmp_test_1);
  tcase_add_test(tc1_1, s21_memcmp_test_2);
  tcase_add_test(tc1_1, s21_memcmp_test_3);
  tcase_add_test(tc1_1, s21_memcpy_test_1);
  tcase_add_test(tc1_1, s21_memcpy_test_2);
  tcase_add_test(tc1_1, s21_memcpy_test_3);
  tcase_add_test(tc1_1, s21_memcpy_test_4);
  tcase_add_test(tc1_1, s21_memset_test_1);
  tcase_add_test(tc1_1, s21_memset_test_2);
  tcase_add_test(tc1_1, s21_memset_test_3);
  tcase_add_test(tc1_1, s21_strncat_test_1);
  tcase_add_test(tc1_1, s21_strncat_test_2);
  tcase_add_test(tc1_1, s21_strncat_test_3);
  tcase_add_test(tc1_1, s21_strchr_test_1);
  tcase_add_test(tc1_1, s21_strchr_test_2);
  tcase_add_test(tc1_1, s21_strchr_test_3);
  tcase_add_test(tc1_1, s21_strchr_test_4);
  tcase_add_test(tc1_1, s21_strchr_test_5);
  tcase_add_test(tc1_1, s21_strlen_test_1);
  tcase_add_test(tc1_1, s21_strlen_test_2);
  tcase_add_test(tc1_1, s21_strlen_test_3);
  tcase_add_test(tc1_1, s21_strpbrk_test_1);
  tcase_add_test(tc1_1, s21_strpbrk_test_2);
  tcase_add_test(tc1_1, s21_strpbrk_test_3);
  tcase_add_test(tc1_1, s21_strpbrk_test_4);
  tcase_add_test(tc1_1, s21_strpbrk_test_5);
  tcase_add_test(tc1_1, s21_strerror_test_1);
  tcase_add_test(tc1_1, s21_strerror_test_2);
  tcase_add_test(tc1_1, s21_strerror_test_3);
  tcase_add_test(tc1_1, s21_strncmp_test_1);
  tcase_add_test(tc1_1, s21_strncmp_test_2);
  tcase_add_test(tc1_1, s21_strncmp_test_3);
  tcase_add_test(tc1_1, s21_strncmp_test_4);
  tcase_add_test(tc1_1, s21_strncmp_test_5);
  tcase_add_test(tc1_1, s21_strcspn_test_1);
  tcase_add_test(tc1_1, s21_strcspn_test_2);
  tcase_add_test(tc1_1, s21_strcspn_test_3);
  tcase_add_test(tc1_1, s21_strncpy_test_1);
  tcase_add_test(tc1_1, s21_strncpy_test_2);
  tcase_add_test(tc1_1, s21_strncpy_test_3);
  tcase_add_test(tc1_1, s21_strrchr_test_1);
  tcase_add_test(tc1_1, s21_strrchr_test_2);
  tcase_add_test(tc1_1, s21_strrchr_test_3);
  tcase_add_test(tc1_1, s21_strstr_test_1);
  tcase_add_test(tc1_1, s21_strstr_test_2);
  tcase_add_test(tc1_1, s21_strstr_test_3);
  tcase_add_test(tc1_1, s21_strtok_test_1);
  tcase_add_test(tc1_1, s21_strtok_test_2);
  tcase_add_test(tc1_1, s21_strtok_test_3);
  tcase_add_test(tc1_1, s21_sprintf_test_d);
  tcase_add_test(tc1_1, s21_sprintf_test_s);
  tcase_add_test(tc1_1, s21_sprintf_test_c);
  tcase_add_test(tc1_1, s21_sprintf_test_u);
  tcase_add_test(tc1_1, s21_sprintf_test_f);
  tcase_add_test(tc1_1, s21_to_lower_test);
  tcase_add_test(tc1_1, s21_to_upper_test);
  tcase_add_test(tc1_1, s21_insert_test);
  tcase_add_test(tc1_1, s21_trim_test);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
